# -*- coding: utf-8 -*-
"""numpy exercises

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12gp3y-CmIEJiHrtWqp6xiBNVJCycUUlh
"""

import numpy as np

def determinant2x2(vec1, vec2):
  if len(vec1)!=len(vec2) or len(vec1)!=2:
    return "invalid shapes"
  result=(vec1[0]*vec2[1])-(vec1[1]*vec2[0])
  return result
